### ISSUE TITLE
GamesNativeSDK Not authorizing: no client

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#24]
There is a new release of Google Play Services (8.3) or rev28 as the android installer calls it.

I dropped in the google-play-services_lib as a replacement in my project, and now, the login no longer works.

I/GamesNativeSDK(  322): Connecting to Google Play...
E/GamesNativeSDK(  322): Not authorizing: no client.

Is the cpp SDK v 2.0 compatible with the latest Google Play Services (8.3)?
It does not seem to be the case!

  bram

**Comment by ggfan** [comment]
It should be fixed with previous checkin, and this checkin with android studio build should also address it automatically.  the reason behind is that new lib depends on android-support-v4.jar, just add link to it, it will be fine:
- Android Studio / build.gradle automatically handles it inside module build.gralde
- from ant build, just drop it into the libs directory
- from eclipse, add dependencies, and also drop it into the libs folder INSIDE eclipse IDE

check it out, if not working, please re-open this issue.
